### ISSUE TITLE
Would it be possible to only have the commenti controller without having the custom style?

### ISSUE THREAD

**Issue by barbaldo** [defensestation/blocknote-comments#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hsingh-ds** [comment]
@barbaldo The plugin requires a specific comment style to function correctly. It uses these comments as custom tags to identify and process the commented text. Without this, the plugin won’t recognise the relevant sections, and it won’t work as expected.
